// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTAs6zOmZSd_3avM17x62qVU_Gat7dKso',
    appId: '1:1024396750145:web:50f7a262f32f5775fcc5c0',
    messagingSenderId: '1024396750145',
    projectId: 'aplicacion-8afa2',
    authDomain: 'aplicacion-8afa2.firebaseapp.com',
    storageBucket: 'aplicacion-8afa2.firebasestorage.app',
    measurementId: 'G-W0NMHT72W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDli9jR2xWzgavjT--wffsBl6UmYKsaH4k',
    appId: '1:1024396750145:android:60c772d466b0522afcc5c0',
    messagingSenderId: '1024396750145',
    projectId: 'aplicacion-8afa2',
    storageBucket: 'aplicacion-8afa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiM9pcq01VuYs1x5dKM8Z8EunGiKWs7Ns',
    appId: '1:1024396750145:ios:c9f0bea36e52b5a5fcc5c0',
    messagingSenderId: '1024396750145',
    projectId: 'aplicacion-8afa2',
    storageBucket: 'aplicacion-8afa2.firebasestorage.app',
    iosBundleId: 'com.example.aplicacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiM9pcq01VuYs1x5dKM8Z8EunGiKWs7Ns',
    appId: '1:1024396750145:ios:c9f0bea36e52b5a5fcc5c0',
    messagingSenderId: '1024396750145',
    projectId: 'aplicacion-8afa2',
    storageBucket: 'aplicacion-8afa2.firebasestorage.app',
    iosBundleId: 'com.example.aplicacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTAs6zOmZSd_3avM17x62qVU_Gat7dKso',
    appId: '1:1024396750145:web:508583b81751831afcc5c0',
    messagingSenderId: '1024396750145',
    projectId: 'aplicacion-8afa2',
    authDomain: 'aplicacion-8afa2.firebaseapp.com',
    storageBucket: 'aplicacion-8afa2.firebasestorage.app',
    measurementId: 'G-CGEMGT44RZ',
  );
}
